name: Robot Framework Tests API - Department Status

on: push

jobs:
    
  test:
    name: Department Status
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install robotframework
        pip install robotframework-requests
        pip install robotframework-seleniumlibrary

    - name: Run Robot Framework tests API Department List
      run: |
        robot -d results Supernatural/Department-Status

    - name: Archive Robot Framework results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: robot-results
        path: ./